### ISSUE TITLE
This GLB file cannot be opened with online3DViewer, but it can be opened using three.js's gltfLoader.

### ISSUE THREAD

**Issue by heningyuan6256** [kovacsv/Online3DViewer#426] opened 2023-10-15 14:40 UTC
**Describe the bug**

[test.glb.zip](https://github.com/kovacsv/Online3DViewer/files/12909817/test.glb.zip)
This GLB file cannot be opened with online3DViewer, but it can be opened using three.js's gltfLoader.

**To Reproduce**

Open this file with online3DViewer.

**Expected behavior**

online3DViewer can load this file just like in the image

**Screenshots**

<img width="1676" alt="截屏2023-10-15 下午10 40 02" src="https://github.com/kovacsv/Online3DViewer/assets/64188102/f33f856a-c3f6-4c56-8eb4-5c11b26cb2fd">

**Comment by kovacsv** [comment] 2023-10-15 16:47
This is because lines are not supported yet. I close this as a duplicate of #423.

**Closed by kovacsv** 2023-10-15 16:47 UTC
Labels: bug, website
