### ISSUE TITLE
to view lines not only surfaces/solids of .3dm (Rhino3d)

### ISSUE THREAD

**Issue by gairteh** [kovacsv/Online3DViewer#411] opened 2023-07-31 08:17 UTC
I'm really glad that I can view .3dm files on my phone! But it shows only surfaces/solids and not lines. For my work, I draw house plans in Rhino3D. We use lines a lot more than surfaces/solids. Is it possible to view lines as well?

**Comment by paireks** [comment] 2023-08-01 13:57
Currently as far as I know viewer does not support displaying curves. One of the tricks I use in these cases is I convert curves into 3d pipes :) I personally create mesh pipes, but in Rhino you could do it e.g. by converting curves to regular pipes, it should work as well.

**Comment by kovacsv** [comment] 2023-08-06 08:49
You can turn on lines in the setting (not available on all mobile phones, depends on the screen size and orientation). These are automatically generated lines based on the geometry. Standalone lines are not supported at the moment.

**Comment by kovacsv** [comment] 2023-10-07 17:31
Close as duplicate of: #423.

**Closed by kovacsv** 2023-10-07 17:31 UTC
Labels: enhancement, website
