### ISSUE TITLE
display transparent parts and hidden/displayed parts on phone

### ISSUE THREAD

**Issue by Dodoturtle** [kovacsv/Online3DViewer#296] opened 2022-08-01 17:49 UTC
**Describe the solution you'd like**

We recommend adding the ability to display transparent models, as well as the ability to select hidden and displayed components on the phone

**Comment by kovacsv** [comment] 2022-10-25 19:53
Duplicate of https://github.com/kovacsv/Online3DViewer/issues/193.

**Closed by kovacsv** 2022-10-25 19:53 UTC
Labels: enhancement, website
