### ISSUE TITLE
Import line information from glTF

### ISSUE THREAD

**Issue by N3GIS** [kovacsv/Online3DViewer#421] opened 2023-10-01 13:36 UTC
**Describe the solution you'd like**

I found that the line information in glb did not parse well, I compared the editor, babylon.js and playCanvas .js of three.js, they all display lines normally, and the link below is the glb file I tested.

[https://drive.google.com/file/d/1w-lugrzDi8uICOl0Lsk5hPv18XbTifUL/view?usp=sharing](url)
[https://drive.google.com/file/d/1KG9UldHQtF7by6hR3wyCdzxXqrW8CYec/view?usp=sharing](url)

![image](https://github.com/kovacsv/Online3DViewer/assets/7942057/9d8590b7-bde1-48d6-b243-67cc5a1bf920)
![image](https://github.com/kovacsv/Online3DViewer/assets/7942057/b96726b4-279c-4fc3-8202-1198c20dc25f)
![image](https://github.com/kovacsv/Online3DViewer/assets/7942057/06ac9118-6950-48a6-8a6a-6ce73d709b8d)
![image](https://github.com/kovacsv/Online3DViewer/assets/7942057/050b6c4c-0cca-4993-b52a-62732db6ded1)

**Comment by kovacsv** [comment] 2023-10-07 17:26
Importing lines is not supported at the moment. The edges you can see are auto generated from the 3D model with the given threshold, so this is why they are not perfect.

**Comment by kovacsv** [comment] 2023-10-07 17:31
Close as duplicate of: #423.

**Closed by kovacsv** 2023-10-07 17:31 UTC
Labels: enhancement, website
