### ISSUE TITLE
Support models with animation

### ISSUE THREAD

**Issue by ahnuhxw** [kovacsv/Online3DViewer#240] opened 2022-04-05 10:56 UTC
**Describe the solution you'd like**

Hope to support 3D models with animation

**Comment by danieldownes** [comment] 2023-02-12 08:51
This is a duplicate of an older issue: https://github.com/kovacsv/Online3DViewer/issues/162

Suggestion closing this one.

**Closed** 2023-02-12 16:32 UTC
Labels: enhancement, website
