### ISSUE TITLE
(feature-request): Add typescript with the npm package

### ISSUE THREAD

**Issue by Aarbel** [kovacsv/Online3DViewer#326] opened 2022-12-05 14:04 UTC
Thanks a lot @kovacsv for all this amazing package= https://www.npmjs.com/package/online-3d-viewer.

Can you provide typescript or better definition with it ?

Also bringing size optimisation would be a best, with modules when importing it.

Thanks a lot for your help

```
Could not find a declaration file for module 'online-3d-viewer'. '/node_modules/online-3d-viewer/build/o3dv.min.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/online-3d-viewer` if it exists or add a new declaration (.d.ts) file containing `declare module 'online-3d-viewer';`ts(7016)
```

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/25119847/205657359-6798f5e9-2780-4d49-a4eb-2a4b8479adb2.png">

**Comment by kovacsv** [comment] 2022-12-06 11:49
Duplicate of #329.

**Closed by kovacsv** 2022-12-06 11:49 UTC
Labels: engine
